name: PointsX
version: 1.0
main: org.josesilveiraa.pointsx.PointsX
api-version: 1.16
softdepend: [ PlaceholderAPI, MVdWPlaceholderAPI ]
authors: [ Josesilveiraa ]
description: An advanced points plugin
